#ifndef CT_METRICS_H
#define CT_METRICS_H
#include <stdint.h>

typedef enum {
    CT_METRIC_CONNECTIONS_ACCEPTED_TOTAL,
    CT_METRIC_CONNECTIONS_REJECTED_TOTAL,
    CT_METRIC_ACTIVE_STREAMS,
    CT_METRIC_PENDING_STREAMS,
    CT_METRIC_STREAMS_OPENED_TOTAL,
    CT_METRIC_STREAMS_CLOSED_TOTAL,
    CT_METRIC_STREAMS_FAILED_TOTAL,
    CT_METRIC_WORK_IDLE,
    CT_METRIC_WORK_ACTIVE,
    CT_METRIC_WORK_CONNECT_FAILURES_TOTAL,
    CT_METRIC_CONTROL_RECONNECTS_TOTAL,
    CT_METRIC_BYTES_C2S_TOTAL,
    CT_METRIC_BYTES_S2C_TOTAL,
    CT_METRIC_BUFFER_BYTES_CURRENT,
    CT_METRIC_BUFFER_BYTES_PEAK,
    CT_METRIC_AEAD_FAILURES_TOTAL,
    CT_METRIC_AUTH_FAILURES_TOTAL,
    CT_METRIC_RESOURCE_LIMIT_REJECTIONS_TOTAL,
    CT_METRIC_UDP_SESSIONS_ACTIVE,
    CT_METRIC_UDP_SESSIONS_CREATED_TOTAL,
    CT_METRIC_UDP_SESSIONS_EXPIRED_TOTAL,
    CT_METRIC_UDP_SESSIONS_REJECTED_TOTAL,
    CT_METRIC_UDP_DATAGRAMS_C2S_TOTAL,
    CT_METRIC_UDP_DATAGRAMS_S2C_TOTAL,
    CT_METRIC_UDP_BYTES_C2S_TOTAL,
    CT_METRIC_UDP_BYTES_S2C_TOTAL,
    CT_METRIC_UDP_DATAGRAMS_DROPPED_TOTAL,
    CT_METRIC_UDP_DATAGRAMS_OVERSIZED_TOTAL,
    CT_METRIC_UDP_REPLAY_DROPPED_TOTAL,
    CT_METRIC_UDP_AEAD_FAILURES_TOTAL,
    CT_METRIC_UDP_LOCAL_SEND_FAILURES_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_V1_CONNECTIONS_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_V2_CONNECTIONS_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_DISABLED_CONNECTIONS_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_HEADER_FAILURES_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_MODE_MISMATCH_TOTAL,
    CT_METRIC_PROXY_PROTOCOL_LOCAL_WRITE_FAILURES_TOTAL,
    CT_METRIC_COUNT
} ct_metric_id;

void ct_metric_inc(ct_metric_id id);
void ct_metric_add(ct_metric_id id, uint64_t value);
void ct_metric_sub(ct_metric_id id, uint64_t value);
void ct_metric_dec(ct_metric_id id);
void ct_metric_set(ct_metric_id id, uint64_t value);
uint64_t ct_metric_get(ct_metric_id id);
const char *ct_metric_name(ct_metric_id id);
void ct_metrics_log_snapshot(const char *module);

#endif
