set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(_p "$ENV{CTUNNEL_CROSS_PREFIX}")
if(_p STREQUAL "")
  set(_p mips-linux-gnu-)
endif()
set(CMAKE_C_COMPILER ${_p}gcc)
set(CMAKE_AR ${_p}ar)
set(CMAKE_RANLIB ${_p}ranlib)
set(CMAKE_STRIP ${_p}strip)
set(CMAKE_READELF ${_p}readelf)
set(CMAKE_OBJDUMP ${_p}objdump)
set(CMAKE_SIZE ${_p}size)
