set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(_p "$ENV{CTUNNEL_CROSS_PREFIX}")
if(_p STREQUAL "")
  set(_p x86_64-w64-mingw32-)
endif()
string(REGEX REPLACE "-+$" "" _p "${_p}")
set(_p "${_p}-")
set(CMAKE_C_COMPILER ${_p}gcc)
set(CMAKE_RC_COMPILER ${_p}windres)
set(CMAKE_STRIP ${_p}strip)
set(CMAKE_OBJDUMP ${_p}objdump)
set(CMAKE_SIZE ${_p}size)
